auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ExamTom.com
url: http://tangzhezhi.github.io/tangblog
feed: /atom.xml
author_info: <a href="http://tangzhezhi.github.io/tangblog">ExamTom</a>
