auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: tangblog
url: http://tangzhezhi.github.io/tangblog/
feed: /atom.xml
author_info: <a href="http://tangzhezhi.github.io/tangblog">tangblog</a>
