auto: true
markdown: rdiscount
pygments: true
paginate: 8
permalink: /:year/:month/:day/:title
simple_search: http://google.com/search  #搜索引擎  
title: /tangblog
root: /tangblog                          #博客路径  
url: http://tangzhezhi.github.io/
feed: /atom.xml
author_info: <a href="http://tangzhezhi.github.io/tangblog">tangblog</a>
